# Generated by Django 3.2.7 on 2021-10-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_phone_number"),
        ("people", "0014_migrate_phone_numbers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
    ]
