# Generated by Django 3.2.5 on 2021-10-24 17:02

from django.db import migrations
from core.constants import AGE_OF_MAJORITY
from core.utils import get_age


def is_invalid_person(person):
    is_child = get_age(person.dob) < AGE_OF_MAJORITY
    return is_child and person.user is not None


def delete_invalid_personal_records(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    deleted_records = 0
    for person in Person.objects.all():
        if is_invalid_person(person):
            person.delete()
            deleted_records += 1
    print(f"Invalid records deleted: {deleted_records}")


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_delete_null_person_records"),
    ]

    operations = [
        migrations.RunPython(delete_invalid_personal_records),
    ]
