# Generated by Django 3.2.5 on 2021-10-24 15:41

from uuid import UUID
from django.db import migrations


def is_valid_uuid(string, version=4):
    try:
        uuid_object = UUID(string, version=version)
        return str(uuid_object) == string
    except ValueError:
        return False


def get_username(person):
    username = person.full_name.replace(" ", "").lower()
    hash = person.username.split("-")[1]
    return f"{username}-{hash}"


def update_uuid_usernames(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    updated_records = 0
    for person in Person.objects.all():
        if is_valid_uuid(person.username):
            username = get_username(person)
            person.username = username
            person.save()
            updated_records += 1
    print(f"Finished updating {updated_records} usernames")


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_delete_invalid_person_records"),
    ]

    operations = [
        migrations.RunPython(update_uuid_usernames),
    ]
