# Generated by Django 3.2.7 on 2021-10-27 14:31

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0007_update_uuid_usernames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="family_members",
        ),
        migrations.RemoveField(
            model_name="person",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="person",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people_creators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="full_name",
            field=models.CharField(
                max_length=300, validators=[core.validators.validate_full_name]
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                help_text="This person's user account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A person with that username already exists."
                },
                max_length=50,
                unique=True,
            ),
        ),
    ]
