# Generated by Django 3.2.7 on 2021-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_update_person_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familyrelationship",
            options={"ordering": ["person__username"]},
        ),
        migrations.RemoveConstraint(
            model_name="familyrelationship",
            name="people_familyrelationship_unique_relationships",
        ),
        migrations.RemoveConstraint(
            model_name="familyrelationship",
            name="people_familyrelationship_prevent_self_relationship",
        ),
        migrations.AddConstraint(
            model_name="familyrelationship",
            constraint=models.UniqueConstraint(
                fields=("person", "relative"), name="people_unique_familyrelationship"
            ),
        ),
        migrations.AlterModelTable(
            name="familyrelationship",
            table="people_relationship",
        ),
    ]
