# Generated by Django 3.2.7 on 2021-10-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("people", "0010_rename_familyrelationship_interpersonalrelationship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interpersonalrelationship",
            name="relationship_type",
        ),
        migrations.RemoveField(
            model_name="interpersonalrelationship",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="interpersonalrelationship",
            name="relation",
            field=models.CharField(
                choices=[
                    ("R", "Romantic"),
                    ("M", "Marital"),
                    ("PC", "Parent-child"),
                    ("S", "Sibling"),
                ],
                default="PC",
                help_text="How the person and the relative are associated.",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interpersonalrelationship",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interpersonalrelationship",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="interpersonalrelationship",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="people.person",
            ),
        ),
        migrations.AlterField(
            model_name="interpersonalrelationship",
            name="relative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reverse_relationships",
                to="people.person",
            ),
        ),
    ]
