# Generated by Django 3.2.7 on 2021-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0011_update_interpersonalrelationship_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelationshipType",
        ),
    ]
