# Generated by Django 3.2.7 on 2021-10-27 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("records", "0002_alter_bodytemperature_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BodyTemperature",
            new_name="TemperatureRecord",
        ),
    ]
