# Generated by Django 3.2.7 on 2021-10-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_rename_bodytemperature_temperaturerecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temperaturerecord",
            options={"ordering": ["person__username", "created_at"]},
        ),
        migrations.AlterModelTable(
            name="temperaturerecord",
            table="records_temperature",
        ),
    ]
