# Generated by Django 3.2.7 on 2021-10-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_auto_20211027_1659"),
    ]

    operations = [
        migrations.RenameField(
            model_name="temperaturerecord",
            old_name="temp",
            new_name="body_temperature",
        ),
    ]
